# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# - task: NuGetToolInstaller@1

# - task: NuGetCommand@2
#   inputs:
#     restoreSolution: '$(solution)'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'update CycloneDX -g'
    includeNuGetOrg: true
  
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'CycloneDX'
    arguments: 'dotnetcore_react.sln --out scan'
    includeNuGetOrg: true
- task: NexusIqPipelineTask@1
  inputs:
    nexusIqService: 'iq.ngrok.io'
    applicationId: 'dotnetcore-react-bom'
    stage: 'Build'
    scanTargets: 'scan\*'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $results = Get-ChildItem "D:\a\_tasks\*\*\resources\evaluationResult.json" | Get-Content 
      Write-Host "Nexus Evaluation Results = $($results)"

       
    
